#!/bin/sh
#
# Start the network tap....
# 
# This is a rather manual method of settings things up.
#
# TODO: Implement tunnel using interface file and standard startup mechanisms
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
  start)
	# Initialize eth0
	ifconfig eth0 up
	
	if [ ! -e /dev/br0 ]
	then
		brctl addbr br0
		ip addr flush dev eth0
		brctl addif br0 eth0

		tunctl -u tc
		brctl addif br0 tap0
		ip link set dev br0 up
		ip link set dev tap0 up
		
		
		# Get the IP address
		NETDEVICES="$(awk -F: '/br.:|tr.:/{print $1}' /proc/net/dev 2>/dev/null)"
		for DEVICE in $NETDEVICES; do
		  ifconfig $DEVICE | grep -q "inet addr"
		  if [ "$?" != 0 ]; then
		#   echo -e "\n${GREEN}Network device ${MAGENTA}$DEVICE${GREEN} detected, DHCP broadcasting for IP.${NORMAL}"
			trap 2 3 11
			/sbin/udhcpc -b -i $DEVICE -x hostname:$(/bin/hostname) -p /var/run/udhcpc.$DEVICE.pid >/dev/null 2>&1 &
			trap "" 2 3 11
			sleep 1
		  fi
		done
	fi
	;;
  stop)
	printf "Stopping network..."
	ifconfig eth0 down
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

